# Generated by Django 5.2.5 on 2025-09-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por coma')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.modulo')),
            ],
        ),
    ]
