# Generated by Django 5.2.5 on 2025-09-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diagnosticousuario',
            table='diagnostico_diagnostico',
        ),
    ]
