# Generated by Django 5.2.6 on 2025-09-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_diagnosticousuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='respuestausuario',
            table='diagnostico_respuestadiagnostico',
        ),
    ]
